# Generated by Django 2.2.13 on 2021-04-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voucher_data',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('redeemed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_redeemed', models.BooleanField(default=False)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addr_set', to='voucher.voucher_data')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('voucher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_set', to='voucher.voucher_data')),
            ],
        ),
    ]
