# Generated by Django 2.2.13 on 2021-04-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher_data')),
            ],
        ),
    ]
